# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qIkfcwhLq41LuhaoxOBSNYg6C37ZoqLZ
"""

import numpy as np
from sklearn.preprocessing import StandardScaler
data = [[0,3] , [9,4], [2,7], [1,1]]
scaler=StandardScaler()
scaler.fit(data)
first=scaler.transform(data)
second=scaler.transform([[2,13], [1,4], [10,7], [1,9]])
print(first.sum())
print(second.sum())