# -*- coding: utf-8 -*-
"""Feature Scaling

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17XICykZ7nVBPhBoyDHjXLXBCNSr9aiF2
"""

import numpy as np
from sklearn import preprocessing

#3 training data points and 3 features
X=np.array([[ 1., -1., 2.],
            [ 2., 0., 0.],
            [ 0., 1., -1.]])

#make the mean to be 0 and variance to be 1
X_scaled=preprocessing.scale(X)

X_scaled.mean(axis=0)

X_scaled.std(axis=0)

scaler=preprocessing.StandardScaler()
scaler.fit(X)
scaler.transform(X)

X_test=[[1,1,0]]
scaler.transform(X_test)