# -*- coding: utf-8 -*-
"""Finding Probabilities for Continuous Valued Features

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s0yCbw7sp-ngLCfxUB_uStJpaOruJ-BP
"""

from sklearn import naive_bayes, datasets
from sklearn import model_selection
iris = datasets.load_iris()
X = iris.data
Y = iris.target

X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, test_size=0.25, random_state=
0)

gnb = naive_bayes.GaussianNB() # GAUSSIAN NAIVE BAYES CLASSIFIER
gnb.fit(X_train, Y_train)

y_pred = gnb.predict(X_test)

# Various metrics for understanding how well the model has performed.
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print("Classification Report")
print(classification_report(Y_test,y_pred))
print("Confusion Matrix")
print(confusion_matrix(Y_test,y_pred))
print()
print("Accuracy Score")
print(accuracy_score(Y_test,y_pred) * 100, "%", sep="")