# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1665uY4U5nHJvFUbB1ca8cSgjbE5F3PGV
"""

from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

dataset=datasets.load_breast_cancer()
dataset.target

X_train,X_test,Y_train,Y_test=train_test_split(dataset.data, dataset.target,test_size=0.2,random_state=0)

clf=KNeighborsClassifier()
clf.fit(X_train,Y_train)

clf.score(X_test,Y_test)